-- Add the additional columns one by one
ALTER TABLE PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE 
ADD LABEL_NM STRING;

ALTER TABLE PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE 
ADD GNN_CD STRING;

ALTER TABLE PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE 
ADD STRENGTH_UNITS_TXT STRING;

ALTER TABLE PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE 
ADD STRENGTH_DSC FLOAT;

ALTER TABLE PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE 
ADD CLASS_CD STRING;

ALTER TABLE PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE 
ADD TOP_SELLER_IND STRING;

ALTER TABLE PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE 
ADD DRUG_RANK_NBR INTEGER;

ALTER TABLE PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE 
ADD EXPIRE_DAYS_NBR INTEGER;

ALTER TABLE PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE 
ADD PATIENT_COUNSEL_CD INTEGER;

ALTER TABLE PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE 
ADD PHONE_NOTIFICATION_IND INTEGER;

ALTER TABLE PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE 
ADD PROMISE_DT_CD INTEGER;

ALTER TABLE PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE 
ADD SOURCE_CD INTEGER;

ALTER TABLE PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE 
ADD COMPOUND_IND STRING;

-- Update from NBA5_WITH_DRUG table directly
UPDATE PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE t1
SET 
    LABEL_NM = d.LABEL_NM,
    GNN_CD = d.GNN_CD,
    STRENGTH_UNITS_TXT = d.STRENGTH_UNITS_TXT,
    STRENGTH_DSC = d.STRENGTH_DSC,
    CLASS_CD = d.CLASS_CD,
    TOP_SELLER_IND = d.TOP_SELLER_IND,
    DRUG_RANK_NBR = d.DRUG_RANK_NBR,
    EXPIRE_DAYS_NBR = d.EXPIRE_DAYS_NBR,
    PATIENT_COUNSEL_CD = d.PATIENT_COUNSEL_CD,
    PHONE_NOTIFICATION_IND = d.PHONE_NOTIFICATION_IND,
    PROMISE_DT_CD = d.PROMISE_DT_CD,
    SOURCE_CD = d.SOURCE_CD,
    COMPOUND_IND = d.COMPOUND_IND
FROM PL_APP_RPHAI.RAW_RPHAI.NBA5_WITH_DRUG d
WHERE d.MESSAGE_ID = t1.MESSAGE_ID;
