-- Add the additional columns 
ALTER TABLE PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE 
ADD COLUMN LABEL_NM STRING,
ADD COLUMN GNN_CD STRING,
ADD COLUMN STRENGTH_UNITS_TXT STRING,
ADD COLUMN STRENGTH_DSC FLOAT,
ADD COLUMN CLASS_CD STRING,
ADD COLUMN TOP_SELLER_IND STRING,
ADD COLUMN DRUG_RANK_NBR INTEGER,
ADD COLUMN EXPIRE_DAYS_NBR INTEGER,
ADD COLUMN PATIENT_COUNSEL_CD INTEGER,
ADD COLUMN PHONE_NOTIFICATION_IND INTEGER,
ADD COLUMN PROMISE_DT_CD INTEGER,
ADD COLUMN SOURCE_CD INTEGER,
ADD COLUMN COMPOUND_IND STRING;

-- Update from NBA5_WITH_DRUG table directly
UPDATE PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE t1
SET 
    LABEL_NM = d.LABEL_NM,
    GNN_CD = d.GNN_CD,
    STRENGTH_UNITS_TXT = d.STRENGTH_UNITS_TXT,
    STRENGTH_DSC = d.STRENGTH_DSC,
    CLASS_CD = d.CLASS_CD,
    TOP_SELLER_IND = d.TOP_SELLER_IND,
    DRUG_RANK_NBR = d.DRUG_RANK_NBR,
    EXPIRE_DAYS_NBR = d.EXPIRE_DAYS_NBR,
    PATIENT_COUNSEL_CD = d.PATIENT_COUNSEL_CD,
    PHONE_NOTIFICATION_IND = d.PHONE_NOTIFICATION_IND,
    PROMISE_DT_CD = d.PROMISE_DT_CD,
    SOURCE_CD = d.SOURCE_CD,
    COMPOUND_IND = d.COMPOUND_IND
FROM PL_APP_RPHAI.RAW_RPHAI.NBA5_WITH_DRUG d
WHERE d.MESSAGE_ID = t1.MESSAGE_ID;
