-- First add the additional drug-related columns
ALTER TABLE PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE 
ADD COLUMN LABEL_NM STRING,
ADD COLUMN GNN_CD STRING,
ADD COLUMN STRENGTH_UNITS_TXT STRING,
ADD COLUMN STRENGTH_DSC FLOAT,
ADD COLUMN CLASS_CD STRING,
ADD COLUMN TOP_SELLER_IND STRING,
ADD COLUMN DRUG_RANK_NBR INTEGER,
ADD COLUMN EXPIRE_DAYS_NBR INTEGER,
ADD COLUMN PATIENT_COUNSEL_CD INTEGER,
ADD COLUMN PHONE_NOTIFICATION_IND INTEGER,
ADD COLUMN PROMISE_DT_CD INTEGER,
ADD COLUMN SOURCE_CD INTEGER,
ADD COLUMN COMPOUND_IND STRING;

-- Then update drug-related columns
UPDATE PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE t1
SET 
    LABEL_NM = dr.LABEL_NM,
    GNN_CD = dr.GNN_CD,
    STRENGTH_UNITS_TXT = dr.STRENGTH_UNITS_TXT,
    STRENGTH_DSC = dr.STRENGTH_DSC,
    CLASS_CD = dr.CLASS_CD,
    TOP_SELLER_IND = dr.TOP_SELLER_IND,
    DRUG_RANK_NBR = dr.DRUG_RANK_NBR,
    EXPIRE_DAYS_NBR = dr.EXPIRE_DAYS_NBR
FROM CORE_RX.CURATED_PRODUCT.DRUG dr
WHERE dr.NDC = t1.NDC;

-- Then update prescription fill related columns
UPDATE PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE t1
SET 
    PATIENT_COUNSEL_CD = pf.PATIENT_COUNSEL_CD,
    PHONE_NOTIFICATION_IND = pf.PHONE_NOTIFICATION_IND,
    PROMISE_DT_CD = pf.PROMISE_DT_CD,
    SOURCE_CD = pf.SOURCE_CD,
    COMPOUND_IND = pf.COMPOUND_IND
FROM CORE_RX.CURATED_SCRIPT.PRESCRIPTION_FILL pf
WHERE pf.STORE_NBR = t1.STORE_NBR
AND pf.RX_NBR = t1.RX_NBR
AND pf.FILL_NBR = t1.FILL_NBR
AND pf.CLAIM_SUBMT_NBR >= t1.CLM_SUBMT_NBR;
